import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js example',
  description: 'Generated by create next app',
  manifest: "/manifest.json", // Ruta al archivo manifest.json de tu PWA
  themeColor: "#000000" // Color de tema para la barra de navegación de la PWA
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
